# Abstract

The proliferation of social media platforms has given rise to a new form of geographic knowledge, where places are no longer only physically grounded, but also digitally manifested through informal communication. The way locations are described on these platforms embeds the informal geographic knowledge that individuals use to form their notion of place, which has been traditionally constrained within the subconscious of individuals, or conceptualised using active participation methods through surveys, mapping exercises, or volunteered geographic information. Instead, communication between users on these platforms generates this place-based knowledge in a more comprehensive and larger volume than previously possible, generating insights into how broader populations experience, interpret and construct the notion of 'place'.

Despite the abundance of natural language text on these social media platforms, much emphasis has been placed on the explicit geographic markers in these data, that primarily exist as geotags. Place-based research that considers social media data therefore typically focusses on the generation of vague semantic regions, where geotagged locations often do not directly correlate with formal administrative definitions. While these works give insight into the place-based knowledge that social media users contribute, there is a greater depth of knowledge that may be directly harvested through the informal text that is abundant on these platforms. In this thesis, I acknowledge that this textual content also possesses an inherent geographic dimension that can be harnessed, by attributing geographic coordinate information to embedded place names. This approach not only enables a substantially larger volume of place-related knowledge to be captured but also facilitates the extraction of embedded semantic information relating to geographic locations, contributed through the informal vernacular geography of social media users.

Moving beyond methods that only consider the geographic component of geotags associated with informal social media communications, this thesis first proposes improvements to geoparsing methods, that enable geographic information to be attributed with place names embedded within natural language text. Geoparsing allows for specific geographic coordinate information to be attributed with this unstructured social media text, capturing informal vernacular geographic information through the associated semantic context of identified locations. With this established, this thesis considers how a large source of UK-specific informal text from the social media website Reddit may be analysed geographically to directly capture this knowledge. Comments are first explored from the perspective of mental maps, where the perceived cognitive associations between locations within the UK demonstrate varying levels of distance decay. Following this, this thesis explores how semantic associations with locational mentions may be captured through embeddings generated through a large language model; referred to as their semantic footprints. These footprints are demonstrated to exhibit geographically cohesive variation, and spatial autocorrelation which is broadly associated with formal national boundaries of the UK.

This thesis aims to explore how place-based geographic knowledge can be captured from informal social media text. The methodologies developed allow for place to be represented from a perspective not considered previously, utilising the depth of semantic information that accompanies place names embedded within informal communication. Results generated demonstrate that geographic information extracted from text does broadly conform with established geographic concepts, but with deviations that would be expected with informal place-based knowledge. The overall strength of cognitive associations between locations identified in our corpus was found to be inversely proportional to the distance between them, a distance decay effect that is commonly observed in real-world geographic environments. However, this effect was highly regional, weaker between cities where cultural associations are stronger and where perceived distance may be shorter compared with reality. Similarly, semantic information associated with locational mentions in this corpus exhibits spatial heterogeneity, but with distinct geographically cohesive clusters, particularly within Wales, Scotland and London.
