{{< include 00_abstract.qmd >}}

\onehalfspacing

# Introduction {#sec-fullintroduction}

The proliferation of social media platforms has given rise to a new form of geographic knowledge, where places are no longer only physically grounded, but also digitally manifested through informal communication. The way locations are described on these platforms embeds informal geographic knowledge that individuals use to form their notion of geographic 'place', which has been traditionally constrained within the subconscious of individuals, conceptualised through active participation methods through surveys, mapping exercises, or volunteered geographic information. Instead, communication between users on these platforms generates this place-based knowledge in a more comprehensive and larger volume than previously possible, generating insights into how broader populations experience, interpret and construct a sense of place.

While most research has primarily focussed on explicit geographic markers on these platforms through geotags, an alternative source of geographic knowledge resides within the accompanying informal natural language text, which exists in a much greater volume and complexity. This thesis proposes how the notion of place is captured through social media text, generating insights into a collective understanding of informal geography, built from an aggregate perspective, and generated through communication between a multitude of individuals.

## Background

The concept of 'place' is fundamental in geography, allowing for the study of the relationship between people and their geographic environment. Place encompasses the cultural and social aspects that relate people with geographic locations, and the ways they interact and shape their environment [@cresswell2014]. Unlike structured administrative datasets, place-focussed geographic information represents informal geographic knowledge, which more closely aligns with the way people perceive geography [@goodchild2011a].

Foundational work conceptualised this knowledge through mental maps [@lynch1964], suggesting that people construct their cognitive representations of their geographic environment. These mental maps incorporate specific features like landmarks or borders and are generated through physical interactions, perceptions, and interpretations of geographic environments. Importantly, these mental maps incorporate a variety of biases that often do not correlate with formal administrative definitions. For example, they may emphasise features that are considered important or the perceived distance between locations can be influenced by their transport connections.

Early attempts at the physical generation of these maps primarily relied on participatory mapping methodologies, where individuals were asked to sketch geographic features from memory [@lynch1964;@pocock1976;@montello2003a;@haney1978;@canter1977;@murray1979;@lee1973;@gould1986;@goodey1974]. These however are limited in scope, given the reliance on individuals who are willing to actively participate, and the time taken to manually generate these maps. Additionally, it is difficult for individuals to conceptualise certain features of mental maps, meaning their scope was traditionally constrained to the formalisation of pre-existing geographic concepts, like the borders of vague regions. More abstract concepts like quantifying cultural similarities or the perceived distance between cities are more complex for individuals to externalise, despite many likely having subconscious opinions regarding these geographically related concepts.

More recently, works have made use of the abundance of informal communication through social media platforms, where grounded geographic information exists as a by-product of digital social interactions. Popular social media platforms like Twitter embed geographic information alongside microblog messages through geotags, which represent the location of a user at the time of communication. Many works theorise that, unlike geographic information obtained through pre-existing and structured administrative data sources, geotags present a view of geography that more directly aligns with the concept of 'place' [@quesnot2015;@sui2011;@sui2009;@hollenstein2010;@cresswell2014;@wolter2018;@goodchild2011a;@purves2011]. While traditional formalisations of space are built 'top-down', meaning boundaries and names are generated primarily by government organisations [@agnew2005], these works note that place may be more accurately captured through a 'bottom-up' approach, built from the collective knowledge of individuals whose geographic knowledge is developed through experience, rather than formal definitions [@sui2011].

## Research Gaps

While many works have considered the ability to capture informal and experiential geographic knowledge from social media, they typically only consider geotags as a geographic component. Few therefore have considered the ability to capture geographic knowledge from the natural language text associated with these social media platforms. This place-based knowledge is generated through 'vernacular geography', which describes the natural language used when informally describing geographic locations [@gao2017a;@goodchild2011;@waters2003;@hollenstein2008]. The ability to consider the vernacular geography of text in social media presents several benefits over geotags. First, geotags are not always a feature of social media platforms, and for platforms like Twitter, they are only present in a very low volume [@leetaru2013]. Text instead is a primary feature of social media, present in a much more abundant volume and passively generated through informal communication between users. Arguably, text itself can more appropriately generate place-based knowledge; while geotags only provide single-coordinate information, the depth of semantic information available through text in theory presents a deeper connection with informal geographic knowledge.

Geographic information in text primarily exists as place names. These place names are often attributable to geographic locations in space and contribute informal geographic information when associated with informal communications between individuals on social media platforms. The task of attributing coordinate information with place names identified in unstructured text is typically known as geoparsing. Such methods are most frequently associated with information retrieval literature, where search results frequently need to consider whether a natural language query incorporates geographic information [@purves2018]. There has however been little focus on this task from the perspective of geographic research, despite there being a clear motivation to expand the volume of informal geographic information available for place-based research, to move beyond solely focussing on geotags.

Existing geoparsing systems are typically built with the consideration that querying is unrestricted in geographic scope, meaning all known place names on Earth are usually resolved, using a global gazetteer like [GeoNames](https://geonames.org). Due to this, geoparsing models tend to primarily resolve place names no smaller than city level, meaning fine-grained locations like street names that frequently appear in natural language are ignored. When identifying place names, these models tend to build on existing natural language processing (NLP) research relating to Named Entity Recognition (NER), where place names are not the primary focus, meaning performance is limited. Finally, the corpora used to train NER models are built with more structured language in mind, meaning they struggle with more informal text like social media.

Place names embedded within informal social media posts contribute informal geographic knowledge from individuals, which may be harvested to contribute to a place-based view of geography. First improvements to geoparsing methodologies are considered in @sec-transformer, where a methodology is developed to ensure that a more accurate and comprehensive recall of place names may be extracted from informal social media. Once achieved, this task and data specific geoparsing system presents the opportunity to explore place-based geographic knowledge from an alternative form of social media data that few works have previously considered in detail, with empirical work undertaken in @sec-connections and @sec-footprint.

## Aims

To address the research gaps outlined above, this thesis outlines three key aims, which form three empirical chapters. The first aim of this thesis describes the methods and theory required to accurately extract geographic knowledge from existing sources of informal natural language text. The second and third aim then build on this chapter and consider the ability to generate place-based geographic insights from extracted place names.

> **Aim 1:** _Improve the results of existing geoparsing systems for place name recognition, and outline the potential for unstructured text to provide informal geographic knowledge._

@sec-transformer addresses this aim by constructing a transformer-based NER model, trained using text with place names manually annotated. This chapter demonstrates that existing models for place names identification do not necessarily perform as well as advertised, primarily due to the lack of task-specific corpora used for training. The methodology presented in this chapter provides the basis for @sec-connections and @sec-footprint, by demonstrating that more accurate geoparsing results may be achieved through training a task and data specific NER model. @sec-transformer also demonstrates that existing sources of online text may be harvested for place names, which augments them with a geographic component that has not been considered in detail in past research. Notably, these place names are often associated with vernacular geography, meaning many are colloquial, or informal, and do not exist within formal gazetteers.

The content of this chapter can be found in the following published journal article:

Berragan, C., Singleton, A., Calafiore, A. & Morley, J. (2023) 'Transformer based named entity recognition for place name extraction from unstructured text', _International Journal of Geographical Information Science_, 37(4), pp.747-766. doi:[10.1080/13658816.2022.2133125](https://doi.org/10.1080/13658816.2022.2133125)

> **Aim 2:** _Generate insights into place-based cognitive associations between locations, through the analysis of locations geoparsed from informal social media text._

@sec-connections utilises the methodology outlined in @sec-transformer to extract place names from a large corpus of social media text from the popular website [Reddit](https://reddit.com), and develops a methodology to associate place names with coordinate information. This chapter then considers the ability to generate place-based cognitive associations between these geoparsed locations, captured through the mental maps of individuals that contributed to the corpus. Associations are built through co-occurring locational mentions, which used to generate a quantifiable measure of association strength. This strength is then assessed with respect to distance decay, to identify whether these associations capture cohesive geographic properties. This chapter demonstrates that social media text does capture a geographic component that appears to strongly correlate with place-based knowledge, but with interesting deviations.

The content of this chapter can be found in the following published journal article:

Berragan, C., Singleton, A., Calafiore, A. \& Morley, J. (2024) 'Mapping Cognitive Place Associations within the United Kingdom through Online Discussion on Reddit', _Transactions of the Institute of British Geographers_. doi:10.1111/tran.12669.

> **Aim 3:** _Examine the geographic variation in the semantic properties of text associated with place names extracted from social media._

@sec-footprint builds on the previous chapter and considers the ability to specifically compare the vernacular geographies emerging from text data in a social media corpus, by analysing and comparing the semantic properties of text relating to locations. This chapter uses a transformer neural network language model to build contextual semantic embeddings for each comment that contains a place name, these were then used to generate an aggregate measure of local authorities across the UK, which we name semantic footprints. This measure demonstrated that the 'semantic footprint' of locations across the UK incorporates geographic properties, and can be used to highlight areas that are semantically isolated from the rest of the country.

The content of this chapter is currently _under review_ for publication in _Computers, Environment and Urban Systems_.
