# A Note on API Restrictions {#sec-api-restrictions}

Alterations made to social media API (particularly Reddit and Twitter), have significantly impeded further research, limiting ease of access by introducing prohibitive costs. Arguably these changes directly conflict with the open standards of the web as originally outlined by Tim Berners-Lee [@berners-lee2010;@cern2023], preventing free and open access to a repository of knowledge that is contributed voluntarily by unpaid users. As a result, despite API restrictions, it is possible to access this data indirectly through automated web-scraping, which is itself a grey area.

The most prominent use of scraped web data comes from the training of Large Languages Models (LLMs) using the [Common Crawl](https://index.commoncrawl.org), and despite using data from both Twitter and Reddit, these LLMs are typically not considered to be infringing on API terms^[[Elon Musk has however suggested that Microsoft illegally trained models using Twitter data.](https://twitter.com/elonmusk/status/1648784955655192577)]. While the removal of open access to the Reddit archive Pushshift does imply that the use of scraped data dumps are unlawful, the legality of web scraping is in fact debatable. For non-commercial use in particular, I personally do not have any ethical concerns in the use of open web data, and present an alternative Reddit data dump through [The Eye](https://the-eye.eu/redarcs/).
